[package]
name = "devol-accounts-kit"
version = "0.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = '0.5.1'
solana-sdk = '1.18.8'
solana-client = '1.18.8'
pyth-sdk-solana = "0.10.1"
solana-program = '1.18.8'