name: Publish to crates.io

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Publish to crates.io
      uses: katyo/publish-crates@v1
      env:
        CARGO_REGISTRY_TOKEN: ${{secrets.CRATES_IO_TOKEN}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
